spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cervejaria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
management.endpoints.web.exposure.include=health,info,metrics,caches
info.app.name=Beer Guide API
info.app.description=API de Cervejarias
info.app.version=1.0.0

spring.jpa.show-sql=true